### ISSUE TITLE
[Question] Can you provide register-specific instruction data with the help of GPT-4V?

### ISSUE THREAD

**Issue by mary-0830** [mu-cai/ViP-LLaVA#13]
### Question

hi, author, 
Thank you for your contribution. Could you please provide this dataset?

**Comment by mu-cai** [comment]
Hi Mary, 

The dataset is here: https://huggingface.co/datasets/mucai/ViP-LLaVA-Instruct/tree/main
It is called [vip-llava_stage3_mix.json](https://huggingface.co/datasets/mucai/ViP-LLaVA-Instruct/blob/main/vip-llava_stage3_mix.json), you can parse the `id` of each dictionary in the list, and you will find the GPT-4V instruction data!

**Comment by mary-0830** [comment]
> Hi Mary,
> 
> The dataset is here: https://huggingface.co/datasets/mucai/ViP-LLaVA-Instruct/tree/main It is called [vip-llava_stage3_mix.json](https://huggingface.co/datasets/mucai/ViP-LLaVA-Instruct/blob/main/vip-llava_stage3_mix.json), you can parse the `id` of each dictionary in the list, and you will find the GPT-4V instruction data!

OK! Thanks for your reply.
